version: "3.4"
services:
  wordpress:
    build:
      context: ./services/wordpress
    image: custom-wordpress:local
    container_name: custom-wordpress
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
  mysql:
    build:
      context: ./services/mysql
    image: custom-mysql:local
    container_name: custom-mysql
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  frontend:
  backend:

volumes:
  db-data:
    name: azurewebapp-sample-multicontainers-db-data
    external: true