version: "3.4"
services:
  wordpress:
    image: ${REGISTRY}/custom-wordpress
    container_name: custom-wordpress
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
  mysql:
    image: ${REGISTRY}/custom-mysql
    container_name: custom-mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  db-data: